# Generated by Django 4.2.7 on 2025-11-14 07:41

from django.db import migrations, models
import django.db.models.deletion
import lpr_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to=lpr_app.models.upload_to_uploads, verbose_name='Original Image')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to=lpr_app.models.upload_to_processed, verbose_name='Processed Image')),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Upload Time')),
                ('processing_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Processing Time')),
                ('api_response', models.JSONField(blank=True, null=True, verbose_name='API Response')),
                ('filename', models.CharField(max_length=255, verbose_name='Filename')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='File Size (bytes)')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Processing Status')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
            ],
            options={
                'verbose_name': 'Uploaded Image',
                'verbose_name_plural': 'Uploaded Images',
                'ordering': ['-upload_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('api_call', 'API Call'), ('success', 'Success'), ('error', 'Error')], max_length=20)),
                ('message', models.TextField()),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='lpr_app.uploadedimage')),
            ],
            options={
                'verbose_name': 'Processing Log',
                'verbose_name_plural': 'Processing Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
