# Generated by Django 4.2.29 on 2026-05-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpr_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='max_retries',
            field=models.PositiveIntegerField(default=2, verbose_name='Max Retries'),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Retry Count'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
